#ifndef LINEADETEXTO_GLOBAL_H
#define LINEADETEXTO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LINEADETEXTO_LIBRARY)
#  define LINEADETEXTOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LINEADETEXTOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LINEADETEXTO_GLOBAL_H
